//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesExceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Banking.Exceptions.ResourceMessagesExceptions", typeof(ResourceMessagesExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi foi possível encontrar o cliente.
        /// </summary>
        public static string CLIENTE_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("CLIENTE_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta não encontrada.
        /// </summary>
        public static string CONTA_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("CONTA_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF já cadastrado.
        /// </summary>
        public static string CPF_CADASTRADO {
            get {
                return ResourceManager.GetString("CPF_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF deve ser válido.
        /// </summary>
        public static string CPF_INVALIDO {
            get {
                return ResourceManager.GetString("CPF_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a data com o seguinte formato válido dd/MM/yyyy.
        /// </summary>
        public static string DATA_FORMATO_INVALIDO {
            get {
                return ResourceManager.GetString("DATA_FORMATO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de deposito não pode ser no futuro.
        /// </summary>
        public static string DATA_NO_FUTURO {
            get {
                return ResourceManager.GetString("DATA_NO_FUTURO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo Data corretamente.
        /// </summary>
        public static string DATA_VAZIA {
            get {
                return ResourceManager.GetString("DATA_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite um Email válido.
        /// </summary>
        public static string EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse Email não pertence a nenhum cliente.
        /// </summary>
        public static string EMAIL_NAO_CADASTRADO {
            get {
                return ResourceManager.GetString("EMAIL_NAO_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Email deve ser preenchido.
        /// </summary>
        public static string EMAIL_VAZIO {
            get {
                return ResourceManager.GetString("EMAIL_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nome deve ser preenchido.
        /// </summary>
        public static string NOME_VAZIO {
            get {
                return ResourceManager.GetString("NOME_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o número da agência.
        /// </summary>
        public static string NUMERO_AGENCIA_VAZIO {
            get {
                return ResourceManager.GetString("NUMERO_AGENCIA_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o número do banco.
        /// </summary>
        public static string NUMERO_BANCO_VAZIO {
            get {
                return ResourceManager.GetString("NUMERO_BANCO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o número da conta.
        /// </summary>
        public static string NUMERO_CONTA_VAZIO {
            get {
                return ResourceManager.GetString("NUMERO_CONTA_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token vazio.
        /// </summary>
        public static string SEM_TOKEN {
            get {
                return ResourceManager.GetString("SEM_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme a senha atual.
        /// </summary>
        public static string SENHA_ATUAL {
            get {
                return ResourceManager.GetString("SENHA_ATUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não deve ser igual a senha atual.
        /// </summary>
        public static string SENHA_IGUAL {
            get {
                return ResourceManager.GetString("SENHA_IGUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha incorreta.
        /// </summary>
        public static string SENHA_INCORRETA {
            get {
                return ResourceManager.GetString("SENHA_INCORRETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo senha deve ter pelo menos 6 caracteres.
        /// </summary>
        public static string SENHA_VAZIA {
            get {
                return ResourceManager.GetString("SENHA_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas devem coincidir.
        /// </summary>
        public static string SENHAS_DEVEM_COINCIDIR {
            get {
                return ResourceManager.GetString("SENHAS_DEVEM_COINCIDIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token no formato inválido. Tente Bearer &lt;token&gt;.
        /// </summary>
        public static string TOKEN_INVALIDO {
            get {
                return ResourceManager.GetString("TOKEN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado.
        /// </summary>
        public static string USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário não tem permissão de acesso.
        /// </summary>
        public static string USUARIO_SEM_PERMISSAO {
            get {
                return ResourceManager.GetString("USUARIO_SEM_PERMISSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor deve ser maior que Zero.
        /// </summary>
        public static string VALOR_TRANSFERENCIA_INVALIDO {
            get {
                return ResourceManager.GetString("VALOR_TRANSFERENCIA_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe um valor válido.
        /// </summary>
        public static string VALOR_TRANSFERENCIA_VAZIO {
            get {
                return ResourceManager.GetString("VALOR_TRANSFERENCIA_VAZIO", resourceCulture);
            }
        }
    }
}
